Feature
gurbuzertunga/formproject pull request #2
Opened 2020-07-13 18:24 UTC by gurbuzertunga

The project has three separate features. 
1- A static nav-bar for Sign in button and password related texts.
2- A form element container with hidden elements according to on click changes.
3- A footer part for necessary copyright.

2020-07-13 19:30 UTC, kitpao requested changes
`# 👋 Hello @gurbuzertunga and @marcode95 ,`

Good job correcting the flow! 👏 I also loved the way your page looks and the way you positioned your elements 🌟

🔍 For this project to be approved, you are still misiing some considerations, please check the comments below and fix them: ⬇️

- [ ] **Note:** For next time, remember to write your commits in imperative tense, as stated in [the article pointed in pathwright](https://www.freecodecamp.org/news/level-you-up-to-awesome-commit-messages-a85558cb90e8/)

### ♻️ Status: Your project requires some additional changes ♻️
___
##### 👉 If you have any doubts you can contact me in slack as @kitpao

🔗 __[Github](https://github.com/kitpao) | [Twitter](https://twitter.com/Kitpao1) | [LinkedIn](https://www.linkedin.com/in/kitzia-paola-vidal/) | [Medium](https://medium.com/@kitpao91)__

2020-07-13 19:30 UTC, kitpao commented on README.md
> +
- [ ] **[MANDATORY]** Your Readme file looks great at first view but it seems it is incomplete, please add the corresponding instructions below this line

2020-07-13 19:30 UTC, kitpao commented on index.html
> +            have read and acknowledge our Privacy Statement.
- [ ] **[MANDATORY]** You are missing the links within an  `<a>` tag and their blue styling for "Terms" and "Privacy Statements", the same is true for the rest of the links in your page: 
 * I forgot my User ID or Password
 * Learn More
 * Privacy Policy
 * Terms of Use
 * Legal
 * Privacy
 * Security
 * Buttons "Sign in" and "Create account" should also be inside `<a>` tags so they are clickable

2020-07-13 19:30 UTC, kitpao commented on index.html
> +          <img src="img/turbotax-logo.png" alt="Turbotax logo" />
- [ ] **[OPTIONAL]** You can use text instead of an image in these products so the text doesn't look blurred

2020-07-13 19:30 UTC, kitpao commented on index.html
> +    </header>
- [ ] **[OPTIONAL]** You can also add the `<nav>` tag for for better use of semantic HTML

2020-07-13 19:30 UTC, kitpao commented on styles.css
> +  align-items: center;
- [ ] **[MANDATORY]** Remember the [good practices of CSS](https://speckyboy.com/good-bad-css-practices/) where the same rule must not be repeated, if you are going to use `align-items: center;` in many items, it's better to use a new class  that has the specific rule and in the HTML put the class in the tag. Example=

HTML
```
<div class="this-class repeated-class">...
<other div class="other-class repeated-class">...
```
CSS:
```
.repeated-class{...}
```

2020-07-13 19:30 UTC, kitpao commented on index.html
> +            <label for="phone-verify" style="margin-left: 10px;"
- [ ] **[MANDATORY]** Please, do not use inline styling, use your css file for this, according to [CSS practices](https://speckyboy.com/good-bad-css-practices/)

2020-07-13 19:30 UTC, kitpao commented on index.html
> +          <p class="form-element" style="font-style: italic;">
- [ ] **[MANDATORY]** Please, do not use inline styling, use your css file for this, according to [CSS practices](https://speckyboy.com/good-bad-css-practices/)

2020-07-14 08:45 UTC, gurbuzertunga commented
Solved minor linters related issues.

2020-07-14 08:57 UTC, elmejdki approved these changes
# status: approved :heavy_check_mark: 
## Great job guys thank you for making the required changes by the previous TSE :100: :+1: :1st_place_medal: 

now you can merge to master your project is approved :checkered_flag: 

## Happy Coding :tophat:

2020-07-14 09:13 UTC, merged